version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: logsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: log-aggregator-redis
    ports:
      - "6379:6379"
    restart: unless-stopped


volumes:
  pgdata: